# 普通僵尸
normal.name=普通僵尸
normal.hp=270
normal.speed=1
normal.damage=10
normal.img_walk=zombies/normal/normal_walk.gif
normal.img_eat=zombies/normal/normal_eat.gif
normal.img_dying=zombies/normal/normal_die.gif
normal.img_die=zombies/normal/normal_die.gif

# 路障僵尸
conehead.name=路障僵尸
conehead.hp=370
conehead.speed=1
conehead.damage=15
conehead.img_walk=zombies/conehead/conehead_walk1.png
conehead.img_eat=zombies/conehead/conehead_eat.gif
conehead.img_die=zombies/conehead/conehead_die.gif 